### ISSUE TITLE
Box shadows

### ISSUE THREAD

**Issue by Anakin86708** [nEbul4/Factorio_Roboport_mk2#6]
I'm not sure if we already had those box shadows during 1.0, but I noticed them after updating the mod to 2.0 (#5).

![image](https://github.com/user-attachments/assets/39e94909-2cc3-4a0f-a30b-ac949e6a40e7)

I just learned how to mod Factorio, so I might take a look at this issue later and simply copy the shadows from the existing roboport.

**Comment by nEbul4** [comment]
Fixed with the 2.0.1 release. Thanks for your help 🫡
