### ISSUE TITLE
Not in Assembler / Crafting Menu

### ISSUE THREAD

**Issue by MessnerYannik** [nEbul4/Factorio_Roboport_mk2#7]
Hello,
I wanted to use this mod for a Spaceage run, but i cannot find the MK2/MK3 Port in the Crafting Menu or the Assembling Machine Menu. I am running Factorio 2.0.24 and Ver. 2.0.1 of the Mod.

**Comment by nEbul4** [comment]
Right now I cant replicate your issue. 
Did you complete the researches for the Roboport MK2 and MK3?

Are there any pointers you can give me to replicate your issue?

**Comment by nEbul4** [comment]
Sorry, didnt want to close the issue, my bad

**Comment by MessnerYannik** [comment]
Found the problem. Sorry for the inconvinience
